spring:
  profiles: # 'local' 프로필을 활성화하여 application-local.yml 설정을 불러오도록 지정
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/cohobby
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      s3:
        bucket: "cohobby"
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
        # credentials: application-local.yml에 분리
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB


springdoc:
  override-with-generic-response: true
jwt:
  secret: ${JWT_SECRET:change-me-32bytes-at-least}  # 최소 32바이트(HS256 기준)
  access-expiration: 3600000
  refresh-expiration: 1209600000


logging:
  level:
    root: INFO
    # 보안 관련 로그를 상세하게 봅니다.
    org.springframework.security: DEBUG
    # JWT 관련 로직이 있는 패키지 경로 (본인 패키지명에 맞게 수정)
    com.backthree.cohobby.config.security: DEBUG